# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--J5b5pjQzmV_bQA8KCHUiXboPZbnGxT
"""

! pip install opencv-python

import cv2
import matplotlib.pyplot as plt
import numpy as np

image = cv2.imread("./photo-1503023345310-bd7c1de61c7d.jpeg")

type(image)

image.shape

plt.imshow(image)

new_image = cv2.cvtColor(image , cv2.COLOR_RGB2BGR)

plt.imshow(new_image)

"""
1. Splitting image channels
"""
r,g,b =cv2.split(new_image)
print('r', r.shape)
print('g', g.shape)
print('b', b.shape)

"""print('r', r.shape)
print('g', g.shape)
print('b', b.shape)"""
new_image = cv2.merge((r,g,b))

s = 10
w = int(new_image.shape[1]*s/100)
h = int(new_image.shape[0]*s/100)
dim = (w,h)
re_size = cv2.resize(new_image ,dim ,interpolation = cv2.INTER_AREA)
re_size.shape

"""
3. rotate operation
"""
(h,w) = new_image.shape[:2]
c = (w/2,h/2)
angle = 90
m = cv2.getRotationMatrix2D(c, angle, 1.0)
rotate_90 = cv2.warpAffine(new_image, m, (h,w))

plt.imshow(rotate_90)

plt.imshow(re_size)